export const tzStrings = [
  { label: "(GMT-11:00) Midway Island, Samoa", value: "Pacific/Midway" },
  { label: "(GMT-10:00) Hawaii", value: "Pacific/Honolulu" },
  { label: "(GMT-09:00) Alaska", value: "US/Alaska" },
  { label: "(GMT-09:00) Alaska (Aleutian Islands)", value: "America/Adak" },
  {
    label: "(GMT-08:00) Pacific Time (US & Canada)",
    value: "America/Los_Angeles",
  },
  { label: "(GMT-08:00) Tijuana, Baja California", value: "America/Tijuana" },
  { label: "(GMT-07:00) Mountain Time (US & Canada)", value: "America/Denver" },
  {
    label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan",
    value: "America/Chihuahua",
  },
  { label: "(GMT-07:00) Arizona", value: "America/Phoenix" },
  { label: "(GMT-07:00) Saskatchewan", value: "Canada/Saskatchewan" },
  { label: "(GMT-06:00) Central America", value: "America/Guatemala" },
  { label: "(GMT-06:00) Central Time (US & Canada)", value: "America/Chicago" },
  {
    label: "(GMT-06:00) Guadalajara, Mexico City, Monterrey",
    value: "America/Mexico_City",
  },
  {
    label: "(GMT-06:00) Bogota, Lima, Quito, Rio Branco",
    value: "America/Bogota",
  },
  {
    label: "(GMT-05:00) Eastern Time (US & Canada)",
    value: "America/New_York",
  },
  {
    label: "(GMT-05:00) Indiana (East)",
    value: "America/Indiana/Indianapolis",
  },
  { label: "(GMT-05:00) Caracas", value: "America/Caracas" },
  { label: "(GMT-04:30) Caracas", value: "America/Caracas" },
  { label: "(GMT-04:00) Atlantic Time (Canada)", value: "America/Halifax" },
  { label: "(GMT-04:00) Santiago", value: "America/Santiago" },
  { label: "(GMT-03:30) Newfoundland", value: "America/St_Johns" },
  {
    label: "(GMT-03:00) Buenos Aires, Georgetown",
    value: "America/Argentina/Buenos_Aires",
  },
  { label: "(GMT-03:00) Brasilia", value: "America/Sao_Paulo" },
  { label: "(GMT-03:00) Greenland", value: "America/Godthab" },
  { label: "(GMT-02:00) Mid-Atlantic", value: "Atlantic/South_Georgia" },
  { label: "(GMT-01:00) Azores", value: "Atlantic/Azores" },
  { label: "(GMT-01:00) Cape Verde Is.", value: "Atlantic/Cape_Verde" },
  {
    label: "(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
    value: "Europe/London",
  },
  {
    label: "(GMT) Casablanca, Monrovia, Reykjavik",
    value: "Africa/Casablanca",
  },
  { label: "(GMT) Casablanca", value: "Africa/Casablanca" },
  { label: "(GMT) Monrovia", value: "Africa/Monrovia" },
  { label: "(GMT) Reykjavik", value: "Atlantic/Reykjavik" },
  { label: "(GMT) Dublin, Edinburgh, Lisbon, London", value: "GMT" },
  { label: "(GMT) Dublin, Edinburgh, Lisbon, London (BST)", value: "BST" },
  {
    label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    value: "Europe/Berlin",
  },
  {
    label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",
    value: "Europe/Paris",
  },
  { label: "(GMT+01:00) West Central Africa", value: "Africa/Lagos" },
  {
    label: "(GMT+02:00) Athens, Bucharest, Istanbul",
    value: "Europe/Istanbul",
  },
  { label: "(GMT+02:00) Cairo", value: "Africa/Cairo" },
  { label: "(GMT+02:00) Harare, Pretoria", value: "Africa/Harare" },
  {
    label: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    value: "Europe/Helsinki",
  },
  { label: "(GMT+02:00) Jerusalem", value: "Asia/Jerusalem" },
  { label: "(GMT+02:00) Jerusalem (IST)", value: "IST" },
  { label: "(GMT+03:00) Baghdad", value: "Asia/Baghdad" },
  { label: "(GMT+03:00) Kuwait, Riyadh", value: "Asia/Riyadh" },
  {
    label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd",
    value: "Europe/Moscow",
  },
  { label: "(GMT+03:00) Nairobi", value: "Africa/Nairobi" },
  { label: "(GMT+03:30) Tehran", value: "Asia/Tehran" },
  { label: "(GMT+04:00) Abu Dhabi, Muscat", value: "Asia/Dubai" },
  { label: "(GMT+04:00) Baku", value: "Asia/Baku" },
  { label: "(GMT+04:00) Tbilisi", value: "Asia/Tbilisi" },
  { label: "(GMT+04:00) Yerevan", value: "Asia/Yerevan" },
  { label: "(GMT+04:30) Kabul", value: "Asia/Kabul" },
  { label: "(GMT+05:00) Ekaterinburg", value: "Asia/Yekaterinburg" },
  { label: "(GMT+05:00) Islamabad, Karachi, Tashkent", value: "Asia/Karachi" },
  {
    label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    value: "Asia/Kolkata",
  },
  { label: "(GMT+05:30) Sri Jayawardenepura", value: "Asia/Colombo" },
  { label: "(GMT+05:45) Kathmandu", value: "Asia/Kathmandu" },
  { label: "(GMT+06:00) Almaty, Novosibirsk", value: "Asia/Almaty" },
  { label: "(GMT+06:00) Astana, Dhaka", value: "Asia/Dhaka" },
  { label: "(GMT+06:30) Yangon (Rangoon)", value: "Asia/Rangoon" },
  { label: "(GMT+07:00) Bangkok, Hanoi, Jakarta", value: "Asia/Bangkok" },
  { label: "(GMT+07:00) Krasnoyarsk", value: "Asia/Krasnoyarsk" },
  {
    label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    value: "Asia/Hong_Kong",
  },
  { label: "(GMT+08:00) Kuala Lumpur, Singapore", value: "Asia/Kuala_Lumpur" },
  { label: "(GMT+08:00) Perth", value: "Australia/Perth" },
  { label: "(GMT+08:00) Taipei", value: "Asia/Taipei" },
  { label: "(GMT+08:00) Ulaanbaatar", value: "Asia/Ulaanbaatar" },
  { label: "(GMT+08:00) Irkutsk", value: "Asia/Irkutsk" },
  { label: "(GMT+08:00) Ulaan Bataar", value: "Asia/Ulaanbaatar" },
  { label: "(GMT+08:45) Eucla", value: "Australia/Eucla" },
  { label: "(GMT+09:00) Osaka, Sapporo, Tokyo", value: "Asia/Tokyo" },
  { label: "(GMT+09:00) Seoul", value: "Asia/Seoul" },
  { label: "(GMT+09:00) Yakutsk", value: "Asia/Yakutsk" },
  { label: "(GMT+09:30) Adelaide", value: "Australia/Adelaide" },
  { label: "(GMT+09:30) Darwin", value: "Australia/Darwin" },
  { label: "(GMT+10:00) Brisbane", value: "Australia/Brisbane" },
  {
    label: "(GMT+10:00) Canberra, Melbourne, Sydney",
    value: "Australia/Sydney",
  },
  { label: "(GMT+10:00) Hobart", value: "Australia/Hobart" },
  { label: "(GMT+10:00) Guam, Port Moresby", value: "Pacific/Guam" },
  { label: "(GMT+10:00) Vladivostok", value: "Asia/Vladivostok" },
  { label: "(GMT+10:30) Lord Howe Island", value: "Australia/Lord_Howe" },
  {
    label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia",
    value: "Asia/Magadan",
  },
  { label: "(GMT+12:00) Auckland, Wellington", value: "Pacific/Auckland" },
  { label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is.", value: "Pacific/Fiji" },
  { label: "(GMT+12:45) Chatham Islands", value: "Pacific/Chatham" },
  { label: "(GMT+13:00) Nuku'alofa", value: "Pacific/Tongatapu" },
  { label: "(GMT+14:00) Kiritimati", value: "Pacific/Kiritimati" },
];
